apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-data-processor-cm
  namespace: factory
  labels:
    app: sqs-kafka-forwarder
data:
  application.yaml: |
    spring:
      application:
        name: streams-app
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      kafka:
        bootstrap-servers: kafka-cluster:9092
        producer:
          bootstrap-servers: kafka-cluster:9092
        consumer:
          enable-auto-commit: false
          isolation-level: read_committed
          auto-offset-reset: latest
        schemaRegistryUrl: http://schema-registry-svc:8081
        autoRegisterSchemas: false
        useSchemasLatestVersion: true
        streams:
          replication-factor: 1
          application-id: DataProcessor
          config:
            mean:
              pressure:
                enabled: true
                windowSize: 15
                labels: [ AfterReturnCompressor, BeforeReturnCompressor, AfterBeginCompressor, BeforeBeginCompressor ]
                inputTopic: pressure
                outputTopicsPostfix: PressureMean
                debugEnabled: true
              temperature:
                enabled: true
                windowSize: 15
                labels: [ BeforeBoiler, AfterBoiler, Return, Begin ]
                inputTopic: temperature
                outputTopicsPostfix: TemperatureMean
                debugEnabled: true
              flowRate:
                enabled: true
                windowSize: 15
                labels: [ CompressedReturn, NotCompressedReturn, Input, Output ]
                inputTopic: flowRate
                outputTopicsPostfix: FlowRateMean
                debugEnabled: true
              gasComposition:
                enabled: true
                windowSize: 15
                labels: [ Begin, Input, Output, Return ]
                inputTopic: gasComposition
                outputTopicsPostfix: GasCompositionMean
                debugEnabled: true
              noiseAndVibration:
                enabled: true
                windowSize: 15
                labels: [ ReturnCompressor, BeginCompressor ]
                inputTopic: noiseAndVibration
                outputTopicsPostfix: NoiseAndVibrationMean
                debugEnabled: true
            performance:
              reaction:
                enabled: true
                joinWindowsDurationMillis: 20000
                inputTopic: InputGasCompositionMean
                outputTopic: OutputGasCompositionMean
                resultTopic: ReactionPerformance
                debugEnabled: true
    server:
      port: 8080
