apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-data-processor-deployment
  namespace: factory
  labels:
    app: kafka-data-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-data-processor
  template:
    metadata:
      labels:
        app: kafka-data-processor
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: kafka-data-processor-cm
      containers:
        - name: kafka-data-processor
          imagePullPolicy: Always
          image: juliantheking/kafka-data-processor
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yaml