apiVersion: v1
kind: Service
metadata:
  name: kafka-data-processor-service
spec:
  selector:
    app: kafka-data-processor-deployment
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 30002