apiVersion: v1
kind: Service
metadata:
  name: kafka-data-processor-service
  namespace: factory
spec:
  selector:
    app: kafka-data-processor-deployment
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080