spring:
  application:
    name: streams-app
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    schemaRegistryUrl: http://localhost:8081
    streams:
      replication-factor: 1
      application-id: DataProcessor
      config:
        pressure:
          enabled: true
          windowSize: 15
          labels: [ AfterReturnCompressor, BeforeReturnCompressor, AfterBeginCompressor, BeforeBeginCompressor ]
          inputTopic: pressure
          outputTopicsPostfix: PressureMean
          debugEnabled: true
        temperature:
          enabled: true
          windowSize: 15
          labels: [ BeforeBoiler, AfterBoiler, Return, Begin ]
          inputTopic: temperature
          outputTopicsPostfix: TemperatureMean
          debugEnabled: true
        flowRate:
          enabled: true
          windowSize: 15
          labels: [ CompressedReturn, NotCompressedReturn, Input, Output ]
          inputTopic: flowRate
          outputTopicsPostfix: FlowRateMean
          debugEnabled: true
        gasComposition:
          enabled: true
          windowSize: 15
          labels: [ Begin, Input, Output, Return ]
          inputTopic: gasComposition
          outputTopicsPostfix: GasCompositionMean
          debugEnabled: true
        noiseAndVibration:
          enabled: true
          windowSize: 15
          labels: [ ReturnCompressor, BeginCompressor ]
          inputTopic: noiseAndVibration
          outputTopicsPostfix: NoiseAndVibrationMean
          debugEnabled: true
server:
  port: 9097